[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.6"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.17"

## Pin this to a release after there is a release > r2018.06.15
[[constraint]]
  branch = "development"
  name = "github.com/globalsign/mgo"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/mongodb/mongo-tools"

[[constraint]]
  branch = "master"
  name = "github.com/otiai10/copy"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/theckman/go-flock"
  version = "0.5.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[prune]
  go-tests = true
  unused-packages = true
