version: "3.4"
services:
  tests:
    build: 
      dockerfile: ./e2e-tests/Dockerfile
      context: ../..
    command: pbm-test
    environment:
      - BACKUP_USER=bcp
      - MONGO_PASS=test1234
      - TESTS_TYPE=sharded
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf:/etc/pbm
      - ./backups:/opt/backups
    depends_on:
      - mongos

  cfg01:
    build:
      dockerfile: ./e2e-tests/docker/mongodb-rs/Dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-4.2}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    hostname: cfg01
    environment:
      - REPLSET_NAME=cfg
      - CONFIGSVR=true
      - MONGO_USER=dba
      - BACKUP_USER=bcp
      - MONGO_PASS=test1234
    command: mongod --configsvr --dbpath /data/db --replSet cfg --bind_ip_all --port 27017 --keyFile /opt/keyFile --storageEngine wiredTiger  --wiredTigerCacheSizeGB 1
    volumes:
      - ./scripts/start.sh:/opt/start.sh
      - data-cfg01:/data/db
  cfg02:
    build:
      dockerfile: ./e2e-tests/docker/mongodb-rs/Dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-4.2}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    hostname: cfg02
    command: mongod --configsvr --dbpath /data/db --replSet cfg --bind_ip_all --port 27017 --keyFile /opt/keyFile --storageEngine wiredTiger --wiredTigerCacheSizeGB 1
    volumes:
      - data-cfg02:/data/db
  cfg03:
    build:
      dockerfile: ./e2e-tests/docker/mongodb-rs/Dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-4.2}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    hostname: cfg03
    command: mongod --configsvr --dbpath /data/db --replSet cfg --bind_ip_all --port 27017 --keyFile /opt/keyFile --storageEngine wiredTiger --wiredTigerCacheSizeGB 1
    volumes:
      - data-cfg03:/data/db
  agent-cfg01:
    container_name: "pbmagent_cfg01"
    user: "1001"
    labels:
      - "com.percona.pbm.app=agent"
      - "com.percona.pbm.agent.rs=cfg"
    environment: 
      - "PBM_MONGODB_URI=mongodb://${BACKUP_USER:-bcp}:${MONGO_PASS:-test1234}@cfg01:27017"
    build: 
      labels:
        - "com.percona.pbm.app=agent"
      dockerfile: ./e2e-tests/docker/pbm-agent/Dockerfile
      context: ../..
    command: pbm-agent
    cap_add:
      - NET_ADMIN
    volumes:
      - ./backups:/opt/backups
    volumes_from:
      - cfg01
  agent-cfg02:
    container_name: "pbmagent_cfg02"
    user: "1001"
    labels:
      - "com.percona.pbm.app=agent"
      - "com.percona.pbm.agent.rs=cfg"
    environment: 
      - "PBM_MONGODB_URI=mongodb://${BACKUP_USER:-bcp}:${MONGO_PASS:-test1234}@cfg02:27017"
    build: 
      labels:
        - "com.percona.pbm.app=agent"
      dockerfile: ./e2e-tests/docker/pbm-agent/Dockerfile
      context: ../..
    command: pbm-agent
    cap_add:
      - NET_ADMIN
    volumes:
      - ./backups:/opt/backups
    volumes_from:
      - cfg02
  agent-cfg03:
    container_name: "pbmagent_cfg03"
    user: "1001"
    labels:
      - "com.percona.pbm.app=agent"
      - "com.percona.pbm.agent.rs=cfg"
    environment: 
      - "PBM_MONGODB_URI=mongodb://${BACKUP_USER:-bcp}:${MONGO_PASS:-test1234}@cfg03:27017"
    build: 
      labels:
        - "com.percona.pbm.app=agent"
      dockerfile: ./e2e-tests/docker/pbm-agent/Dockerfile
      context: ../..
    command: pbm-agent
    cap_add:
      - NET_ADMIN
    volumes:
      - ./backups:/opt/backups
    volumes_from:
      - cfg03

  rs101:
    build:
      dockerfile: ./e2e-tests/docker/mongodb-rs/Dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-4.2}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    hostname: rs101
    environment:
      - REPLSET_NAME=rs1
      - MONGO_USER=dba
      - BACKUP_USER=bcp
      - MONGO_PASS=test1234
      - CONFIGSVR=false
    command: mongod --replSet rs1 --port 27017 --storageEngine wiredTiger --shardsvr  --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - data-rs101:/data/db
      - ./scripts/start.sh:/opt/start.sh
  rs102:
    build:
      dockerfile: ./e2e-tests/docker/mongodb-rs/Dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-4.2}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    hostname: rs102
    command: mongod --replSet rs1 --port 27017 --storageEngine wiredTiger --shardsvr  --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - data-rs102:/data/db
  rs103:
    build:
      dockerfile: ./e2e-tests/docker/mongodb-rs/Dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-4.2}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    hostname: rs103
    command: mongod --replSet rs1 --port 27017 --storageEngine wiredTiger --shardsvr  --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - data-rs103:/data/db
  agent-rs101:
    container_name: "pbmagent_rs101"
    user: "1001"
    labels:
      - "com.percona.pbm.app=agent"
      - "com.percona.pbm.agent.rs=rs1"
    environment: 
      - "PBM_MONGODB_URI=mongodb://${BACKUP_USER:-bcp}:${MONGO_PASS:-test1234}@rs101:27017"
    build: 
      labels:
        - "com.percona.pbm.app=agent"
      dockerfile: ./e2e-tests/docker/pbm-agent/Dockerfile
      context: ../..
    volumes:
      - ./conf:/etc/pbm
      - ./backups:/opt/backups
    volumes_from:
      - rs101
    command: pbm-agent
    cap_add:
      - NET_ADMIN
  agent-rs102:
    container_name: "pbmagent_rs102"
    user: "1001"
    labels:
      - "com.percona.pbm.app=agent"
      - "com.percona.pbm.agent.rs=rs1"
    environment: 
      - "PBM_MONGODB_URI=mongodb://${BACKUP_USER:-bcp}:${MONGO_PASS:-test1234}@rs102:27017"
    build: 
      labels:
        - "com.percona.pbm.app=agent"
      dockerfile: ./e2e-tests/docker/pbm-agent/Dockerfile
      context: ../..
    command: pbm-agent
    cap_add:
      - NET_ADMIN
    volumes:
      - ./backups:/opt/backups
    volumes_from:
      - rs102
  agent-rs103:
    container_name: "pbmagent_rs103"
    user: "1001"
    labels:
      - "com.percona.pbm.app=agent"
      - "com.percona.pbm.agent.rs=rs1"
    environment: 
      - "PBM_MONGODB_URI=mongodb://${BACKUP_USER:-bcp}:${MONGO_PASS:-test1234}@rs103:27017"
    build: 
      labels:
        - "com.percona.pbm.app=agent"
      dockerfile: ./e2e-tests/docker/pbm-agent/Dockerfile
      context: ../..
    command: pbm-agent
    cap_add:
      - NET_ADMIN
    volumes:
      - ./backups:/opt/backups
    volumes_from:
      - rs103
   
  rs201:
    build:
      dockerfile: ./e2e-tests/docker/mongodb-rs/Dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-4.2}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    hostname: rs201
    environment:
      - REPLSET_NAME=rs2
      - MONGO_USER=dba
      - BACKUP_USER=bcp
      - MONGO_PASS=test1234
      - CONFIGSVR=false
    command: mongod --replSet rs2 --port 27017 --storageEngine wiredTiger --shardsvr  --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - data-rs201:/data/db
      - ./scripts/start.sh:/opt/start.sh
  rs202:
    build:
      dockerfile: ./e2e-tests/docker/mongodb-rs/Dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-4.2}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    hostname: rs202
    command: mongod --replSet rs2 --port 27017 --storageEngine wiredTiger --shardsvr  --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - data-rs202:/data/db
  rs203:
    build:
      dockerfile: ./e2e-tests/docker/mongodb-rs/Dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-4.2}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    hostname: rs203
    command: mongod --replSet rs2 --port 27017 --storageEngine wiredTiger --shardsvr  --keyFile /opt/keyFile --wiredTigerCacheSizeGB 1
    volumes:
      - data-rs203:/data/db
  agent-rs201:
    container_name: "pbmagent_rs201"
    user: "1001"
    labels:
      - "com.percona.pbm.app=agent"
      - "com.percona.pbm.agent.rs=rs2"
    environment: 
      - "PBM_MONGODB_URI=mongodb://${BACKUP_USER:-bcp}:${MONGO_PASS:-test1234}@rs201:27017"
    build: 
      labels:
        - "com.percona.pbm.app=agent"
      dockerfile: ./e2e-tests/docker/pbm-agent/Dockerfile
      context: ../..
    command: pbm-agent
    cap_add:
      - NET_ADMIN
    volumes:
      - ./backups:/opt/backups
    volumes_from:
      - rs201
  agent-rs202:
    container_name: "pbmagent_rs202"
    user: "1001"
    labels:
      - "com.percona.pbm.app=agent"
      - "com.percona.pbm.agent.rs=rs2"
    environment: 
      - "PBM_MONGODB_URI=mongodb://${BACKUP_USER:-bcp}:${MONGO_PASS:-test1234}@rs202:27017"
    build: 
      labels:
        - "com.percona.pbm.app=agent"
      dockerfile: ./e2e-tests/docker/pbm-agent/Dockerfile
      context: ../..
    command: pbm-agent
    cap_add:
      - NET_ADMIN
    volumes:
      - ./backups:/opt/backups
    volumes_from:
      - rs202
  agent-rs203:
    container_name: "pbmagent_rs203"
    user: "1001"
    labels:
      - "com.percona.pbm.app=agent"
      - "com.percona.pbm.agent.rs=rs2"
    environment: 
      - "PBM_MONGODB_URI=mongodb://${BACKUP_USER:-bcp}:${MONGO_PASS:-test1234}@rs203:27017"
    build: 
      labels:
        - "com.percona.pbm.app=agent"
      dockerfile: ./e2e-tests/docker/pbm-agent/Dockerfile
      context: ../..
    command: pbm-agent
    cap_add:
      - NET_ADMIN
    volumes:
      - ./backups:/opt/backups
    volumes_from:
      - rs203

  mongos:
    build:
      dockerfile: ./e2e-tests/docker/mongodb-rs/Dockerfile
      context: ../..
      args:
        - MONGODB_VERSION=${MONGODB_VERSION:-4.2}
        - MONGODB_IMAGE=${MONGODB_IMAGE:-percona/percona-server-mongodb}
    hostname: mongos
    command: mongos --port 27017 --bind_ip_all --keyFile /opt/keyFile --configdb cfg/cfg01:27017,cfg02:27017,cfg03:27017
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/sharded/mongos_init.js:/opt/mongos_init.js
    depends_on:
      - cfg01
      - cfg02
      - cfg03
      - rs101
      - rs102
      - rs103
      - rs201
      - rs202
      - rs203

  minio:
    image: minio/minio:RELEASE.2020-01-16T22-40-29Z
    hostname: minio
    # ports:
    #   - "9000:9000"
    volumes:
      - backups:/backups
    environment:
      - "MINIO_ACCESS_KEY=minio1234"
      - "MINIO_SECRET_KEY=minio1234"
    command: server /backups
  createbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minio1234 minio1234;
      /usr/bin/mc mb myminio/bcp;
      exit 0;
      "
volumes:
  backups:
  data-cfg01:
  data-cfg02:
  data-cfg03:
  data-rs101:
  data-rs102:
  data-rs103:
  data-rs201:
  data-rs202:
  data-rs203:

