storage:
    type: s3
    s3:
      endpointUrl: http://minio:9000
      bucket: bcp
      prefix: pbme2etest
      credentials:
        access-key-id: "minio1234"
        secret-access-key: "minio1234"
pitr:
    enabled: true
  
